### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by ErelOzcakirlar** [Thirdpresence-Open/thirdpresence-ad-sdk-android#1] opened 2016-12-08 08:43 UTC
`  compile 'com.thirdpresence.adsdk.sdk:thirdpresence-ad-sdk:1.5@aar'
    compile 'com.thirdpresence.adsdk.mediation.mopub:thirdpresence-mopub-mediation:1.5@aar'`

these are not downloading libraries successfully.
correct form is : 
`  compile 'com.thirdpresence.adsdk.sdk:thirdpresence-ad-sdk:1.5.0@aar'
    compile 'com.thirdpresence.adsdk.mediation.mopub:thirdpresence-mopub-mediation:1.5.0@aar'`

FYI.
Greetings from Funimate :)

**Comment by Thirdpresence-Open** [comment] 2016-12-08 09:48
Thanks for letting know. The version numbers are fixed in related documents. The issue was caused by the script that automatically attach the version number to the document.

**Closed as completed by Thirdpresence-Open** 2016-12-08 09:48 UTC
